### PR TITLE
fix: empty auth

### LINKED ISSUE #6: Proxy to endpoints without auth is broken
Right now you cannot proxy to static resources (like https://sapui5.hana.ondemand.com/resources).

request.js has a line which checks if auth is present

```
if (options.auth) {
```

Your latest change initializes auth with `{}` instead of `null`.

This results in the following error

info ui5-middleware-http-proxy GET /sap-ui-core.js -> https://sapui5.hana.ondemand.com/1.71.27/resources/sap-ui-core.js
Error: no auth mechanism defined
    at Auth.onRequest (...\node_modules\.pnpm\request@2.88.2\node_modules\request\lib\auth.js:132:32)
    at Request.auth (...\node_modules\.pnpm\request@2.88.2\node_modules\request\request.js:1344:14)
    at Request.init (...\node_modules\.pnpm\request@2.88.2\node_modules\request\request.js:381:10)

### PR DESCRIPTION
**Pull request by pwasem**
# fix: empty auth

Fix for passing `auth` as an empty object instead of `null` if no `auth.user` and `auth.pass` are being provided either via `ui5.yaml` or `.env`  

fixes https://github.com/pwasem/ui5-middleware-http-proxy/issues/6

### CODE REVIEW

File: lib/middleware/http-proxy.js [hunk 1]
```diff
@@ -1,18 +1,20 @@
...
   const { HTTP_PROXY_AUTH_USER, HTTP_PROXY_AUTH_PASS } = process.env
-  if (!auth.user) {
+  if (!auth.user && HTTP_PROXY_AUTH_USER) {
     auth.user = HTTP_PROXY_AUTH_USER
   }
-  if (!auth.pass) {
+  if (!auth.pass && HTTP_PROXY_AUTH_PASS) {
     auth.pass = HTTP_PROXY_AUTH_PASS
   }
+  return !lodash.isEmpty(auth) ? auth : null
```
Comment (ghost) [inline lib/middleware/http-proxy.js:17]: I am not a fan of big dependencies for simple checks. Wouldn't `return Object.keys(auth).length ? auth : null` be enough?
